name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: CI on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
          - os: macos-15

    steps:
      - run: swift --version
      - uses: actions/checkout@v4

      - name: test
        run: swift test

      - name: build for release
        run: swift build -c release
